# Generated by Django 3.2 on 2026-04-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={},
        ),
    ]
